buildVariable: false
category:
- SERIF
familyName: Noto Serif Balinese
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifBalinese.glyphs
